import { useState, useRef, useCallback } from "react";
import {
  FaCopy,
  FaRedo,
  FaDownload,
  FaQuoteLeft,
  FaTag,
  FaLanguage,
  FaHeart,
  FaShareAlt,
  FaTwitter,
  FaWhatsapp,
  FaCheck,
} from "react-icons/fa";
import html2canvas from "html2canvas";
import { useUserData } from "../context/UserDataContext";

const QuoteCard = ({ quote, category, language, onGenerateAnother, quoteItem }) => {
  const [copied, setCopied] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const cardRef = useRef(null);
  const { toggleFavorite, isFavorite } = useUserData();

  const favorited = quoteItem ? isFavorite(quoteItem.id) : false;

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(quote);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textArea = document.createElement("textarea");
      textArea.value = quote;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand("copy");
      document.body.removeChild(textArea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [quote]);

  const handleDownload = useCallback(async () => {
    if (!cardRef.current) return;
    try {
      const canvas = await html2canvas(cardRef.current, {
        scale: 2,
        backgroundColor: null,
        useCORS: true,
        logging: false,
      });
      const link = document.createElement("a");
      link.download = `quote-${category.toLowerCase()}-${Date.now()}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (error) {
      console.error("Download failed:", error);
    }
  }, [category]);

  const handleFavorite = useCallback(() => {
    if (quoteItem) toggleFavorite(quoteItem);
  }, [quoteItem, toggleFavorite]);

  const handleShareTwitter = useCallback(() => {
    const text = encodeURIComponent(`"${quote}" — #AIQuotes #Motivation #Inspiration`);
    window.open(`https://twitter.com/intent/tweet?text=${text}`, "_blank", "noopener");
    setShareOpen(false);
  }, [quote]);

  const handleShareWhatsApp = useCallback(() => {
    const text = encodeURIComponent(`"${quote}"\n\n— Generated by AI Quote Generator`);
    window.open(`https://wa.me/?text=${text}`, "_blank", "noopener");
    setShareOpen(false);
  }, [quote]);

  const handleShareCopy = useCallback(async () => {
    const shareText = `"${quote}"\n\n— Category: ${category} | Language: ${language}\nGenerated by AI Quote Generator`;
    await navigator.clipboard.writeText(shareText).catch(() => {});
    setShareCopied(true);
    setTimeout(() => { setShareCopied(false); setShareOpen(false); }, 2000);
  }, [quote, category, language]);

  const charCount = quote.length;

  return (
    <div className="animate-fadeIn w-full max-w-2xl mx-auto">
      {/* Quote Display Card */}
      <div
        ref={cardRef}
        className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-white/90 to-white/60 dark:from-gray-800/90 dark:to-gray-900/60 backdrop-blur-xl border border-white/30 dark:border-gray-700/30 p-8 sm:p-10 shadow-2xl shadow-blue-500/10 dark:shadow-purple-500/10"
      >
        {/* Decorative elements */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-blue-400/20 to-purple-400/20 dark:from-blue-600/10 dark:to-purple-600/10 rounded-full -translate-y-1/2 translate-x-1/2" />
        <div className="absolute bottom-0 left-0 w-24 h-24 bg-gradient-to-tr from-purple-400/20 to-pink-400/20 dark:from-purple-600/10 dark:to-pink-600/10 rounded-full translate-y-1/2 -translate-x-1/2" />

        {/* Favorite button — top right */}
        {quoteItem && (
          <button
            onClick={handleFavorite}
            className={`absolute top-4 right-4 z-10 p-2.5 rounded-xl transition-all duration-300 shadow-sm hover:shadow-md hover:-translate-y-0.5 ${
              favorited
                ? "bg-pink-50 dark:bg-pink-900/30 text-pink-500"
                : "bg-white/70 dark:bg-gray-700/60 text-gray-300 dark:text-gray-500 hover:text-pink-400 hover:bg-pink-50 dark:hover:bg-pink-900/20"
            }`}
            title={favorited ? "Remove from favorites" : "Save to favorites"}
          >
            <FaHeart className={`text-base transition-transform duration-200 ${favorited ? "scale-110" : ""}`} />
          </button>
        )}

        {/* Quote Icon */}
        <div className="relative mb-6">
          <FaQuoteLeft className="text-4xl text-blue-500/30 dark:text-blue-400/30" />
        </div>

        {/* Quote Text */}
        <blockquote className="relative text-xl sm:text-2xl font-medium text-gray-800 dark:text-gray-100 leading-relaxed mb-8">
          {quote}
        </blockquote>

        {/* Meta Info */}
        <div className="relative flex flex-wrap items-center gap-4 text-sm text-gray-500 dark:text-gray-400">
          <span className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 font-medium">
            <FaTag className="text-xs" />
            {category}
          </span>
          <span className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-purple-50 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 font-medium">
            <FaLanguage className="text-xs" />
            {language}
          </span>
          <span className="text-xs text-gray-400 dark:text-gray-500">
            {charCount} characters
          </span>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mt-6 flex-wrap">
        {/* Copy */}
        <button
          onClick={handleCopy}
          className={`w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-medium text-sm transition-all duration-300 shadow-lg hover:shadow-xl hover:-translate-y-0.5 active:translate-y-0 ${
            copied
              ? "bg-green-500 text-white shadow-green-500/25"
              : "bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm text-gray-700 dark:text-gray-200 border border-gray-200 dark:border-gray-600 hover:border-blue-400 dark:hover:border-blue-500 shadow-black/5"
          }`}
        >
          <FaCopy className="text-sm" />
          {copied ? "Copied!" : "Copy Quote"}
        </button>

        {/* Generate Another */}
        <button
          onClick={onGenerateAnother}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-medium text-sm bg-gradient-to-r from-blue-500 to-purple-600 text-white shadow-lg shadow-blue-500/25 hover:shadow-xl hover:shadow-blue-500/30 hover:-translate-y-0.5 active:translate-y-0 transition-all duration-300"
        >
          <FaRedo className="text-sm" />
          Generate Another
        </button>

        {/* Download */}
        <button
          onClick={handleDownload}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-medium text-sm bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm text-gray-700 dark:text-gray-200 border border-gray-200 dark:border-gray-600 hover:border-purple-400 dark:hover:border-purple-500 shadow-lg shadow-black/5 hover:shadow-xl hover:-translate-y-0.5 active:translate-y-0 transition-all duration-300"
        >
          <FaDownload className="text-sm" />
          Download
        </button>

        {/* Share dropdown */}
        <div className="relative w-full sm:w-auto">
          <button
            onClick={() => setShareOpen((p) => !p)}
            className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-medium text-sm bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm text-gray-700 dark:text-gray-200 border border-gray-200 dark:border-gray-600 hover:border-emerald-400 dark:hover:border-emerald-500 shadow-lg shadow-black/5 hover:shadow-xl hover:-translate-y-0.5 active:translate-y-0 transition-all duration-300"
          >
            <FaShareAlt className="text-sm" />
            Share
          </button>

          {shareOpen && (
            <div className="absolute bottom-full mb-2 left-0 sm:left-auto sm:right-0 w-52 rounded-2xl bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 shadow-2xl shadow-black/10 dark:shadow-black/30 overflow-hidden z-30 animate-fadeIn">
              <div className="p-1.5 space-y-0.5">
                <button
                  onClick={handleShareTwitter}
                  className="w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm text-gray-700 dark:text-gray-300 hover:bg-sky-50 dark:hover:bg-sky-900/20 hover:text-sky-600 dark:hover:text-sky-400 transition-all"
                >
                  <FaTwitter className="text-sky-500" />
                  Share on Twitter / X
                </button>
                <button
                  onClick={handleShareWhatsApp}
                  className="w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm text-gray-700 dark:text-gray-300 hover:bg-green-50 dark:hover:bg-green-900/20 hover:text-green-600 dark:hover:text-green-400 transition-all"
                >
                  <FaWhatsapp className="text-green-500" />
                  Share on WhatsApp
                </button>
                <button
                  onClick={handleShareCopy}
                  className="w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm text-gray-700 dark:text-gray-300 hover:bg-blue-50 dark:hover:bg-blue-900/20 hover:text-blue-600 dark:hover:text-blue-400 transition-all"
                >
                  {shareCopied ? <FaCheck className="text-green-500" /> : <FaCopy className="text-blue-400" />}
                  {shareCopied ? "Copied!" : "Copy share text"}
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default QuoteCard;